//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTools.CCDesign.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCTools.CCDesign.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Administrator).
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Chip&apos;s Challenge Level Designer.
        /// </summary>
        internal static string AppTitleSuffix {
            get {
                return ResourceManager.GetString("AppTitleSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [chips temp]
        ///Level{0}={1}
        ///Current Level={0}
        ///PickUpToolSound=blip2.wav
        ///OpenDoorSound=door.wav
        ///ChipDeathSound=bummer.wav
        ///LevelCompleteSound=ditty1.wav
        ///SocketSound=chimes.wav
        ///BlockedMoveSound=oof3.wav
        ///ThiefSound=strike.wav
        ///SoundOnSound=chimes.wav
        ///PickUpChipSound=click3.wav
        ///SwitchSound=pop2.wav
        ///SplashSound=water2.wav
        ///BombSound=hit3.wav
        ///TeleportSound=teleport.wav
        ///TickSound=click1.wav
        ///ChipDeathByTimeSound=bell.wav
        ///Number of Midi Files=3
        ///MidiFile0=chip01.mid
        ///MidiFile1=chip02.mid
        ///MidiFile2=C:\W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CCTemp {
            get {
                return ResourceManager.GetString("CCTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip&apos;s Challenge executable was not found at the specified location. Please set it via Options..
        /// </summary>
        internal static string ChipsChallengeNotFound {
            get {
                return ResourceManager.GetString("ChipsChallengeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chip&apos;s Challenge location is not specified. Please set it via Options..
        /// </summary>
        internal static string ChipsChallengeNotSet {
            get {
                return ResourceManager.GetString("ChipsChallengeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do&amp;n&apos;t save.
        /// </summary>
        internal static string DontSave {
            get {
                return ResourceManager.GetString("DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip&apos;s Challenge Level Designer.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Read-Only).
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
    }
}
