//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}..
        /// </summary>
        internal static string Argument_InvalidBound {
            get {
                return ResourceManager.GetString("Argument_InvalidBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        internal static string Argument_MustBeLess {
            get {
                return ResourceManager.GetString("Argument_MustBeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}..
        /// </summary>
        internal static string Argument_MustBeLessOrEqual {
            get {
                return ResourceManager.GetString("Argument_MustBeLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add or insert the item &apos;{0}&apos; in more than one place. You must first remove it from its current location or clone it..
        /// </summary>
        internal static string Argument_OnlyOneItem {
            get {
                return ResourceManager.GetString("Argument_OnlyOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DefaultTileset {
            get {
                object obj = ResourceManager.GetObject("DefaultTileset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DefaultTilesetImage {
            get {
                object obj = ResourceManager.GetObject("DefaultTilesetImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob - E.
        /// </summary>
        internal static string Description_BlobE {
            get {
                return ResourceManager.GetString("Description_BlobE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob - N.
        /// </summary>
        internal static string Description_BlobN {
            get {
                return ResourceManager.GetString("Description_BlobN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob - S.
        /// </summary>
        internal static string Description_BlobS {
            get {
                return ResourceManager.GetString("Description_BlobS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob - W.
        /// </summary>
        internal static string Description_BlobW {
            get {
                return ResourceManager.GetString("Description_BlobW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string Description_Block {
            get {
                return ResourceManager.GetString("Description_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block - E.
        /// </summary>
        internal static string Description_BlockE {
            get {
                return ResourceManager.GetString("Description_BlockE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block - N.
        /// </summary>
        internal static string Description_BlockN {
            get {
                return ResourceManager.GetString("Description_BlockN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block - S.
        /// </summary>
        internal static string Description_BlockS {
            get {
                return ResourceManager.GetString("Description_BlockS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block - W.
        /// </summary>
        internal static string Description_BlockW {
            get {
                return ResourceManager.GetString("Description_BlockW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Button.
        /// </summary>
        internal static string Description_BlueButton {
            get {
                return ResourceManager.GetString("Description_BlueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Key.
        /// </summary>
        internal static string Description_BlueKey {
            get {
                return ResourceManager.GetString("Description_BlueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Lock.
        /// </summary>
        internal static string Description_BlueLock {
            get {
                return ResourceManager.GetString("Description_BlueLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Wall -&gt; Floor.
        /// </summary>
        internal static string Description_BlueWallFake {
            get {
                return ResourceManager.GetString("Description_BlueWallFake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Wall -&gt; Wall.
        /// </summary>
        internal static string Description_BlueWallReal {
            get {
                return ResourceManager.GetString("Description_BlueWallReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb.
        /// </summary>
        internal static string Description_Bomb {
            get {
                return ResourceManager.GetString("Description_Bomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown Button.
        /// </summary>
        internal static string Description_BrownButton {
            get {
                return ResourceManager.GetString("Description_BrownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug - E.
        /// </summary>
        internal static string Description_BugE {
            get {
                return ResourceManager.GetString("Description_BugE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug - N.
        /// </summary>
        internal static string Description_BugN {
            get {
                return ResourceManager.GetString("Description_BugN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug - S.
        /// </summary>
        internal static string Description_BugS {
            get {
                return ResourceManager.GetString("Description_BugS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug - W.
        /// </summary>
        internal static string Description_BugW {
            get {
                return ResourceManager.GetString("Description_BugW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip in Fire.
        /// </summary>
        internal static string Description_BurningChip {
            get {
                return ResourceManager.GetString("Description_BurningChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burnt Chip.
        /// </summary>
        internal static string Description_BurntChip {
            get {
                return ResourceManager.GetString("Description_BurntChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip.
        /// </summary>
        internal static string Description_Chip {
            get {
                return ResourceManager.GetString("Description_Chip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip - E.
        /// </summary>
        internal static string Description_ChipE {
            get {
                return ResourceManager.GetString("Description_ChipE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip in Exit.
        /// </summary>
        internal static string Description_ChipInExit {
            get {
                return ResourceManager.GetString("Description_ChipInExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip - N.
        /// </summary>
        internal static string Description_ChipN {
            get {
                return ResourceManager.GetString("Description_ChipN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip - S.
        /// </summary>
        internal static string Description_ChipS {
            get {
                return ResourceManager.GetString("Description_ChipS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip Swim - E.
        /// </summary>
        internal static string Description_ChipSwimE {
            get {
                return ResourceManager.GetString("Description_ChipSwimE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip Swim - N.
        /// </summary>
        internal static string Description_ChipSwimN {
            get {
                return ResourceManager.GetString("Description_ChipSwimN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip Swim - S.
        /// </summary>
        internal static string Description_ChipSwimS {
            get {
                return ResourceManager.GetString("Description_ChipSwimS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip Swim - W.
        /// </summary>
        internal static string Description_ChipSwimW {
            get {
                return ResourceManager.GetString("Description_ChipSwimW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip - W.
        /// </summary>
        internal static string Description_ChipW {
            get {
                return ResourceManager.GetString("Description_ChipW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning Machine.
        /// </summary>
        internal static string Description_CloningMachine {
            get {
                return ResourceManager.GetString("Description_CloningMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirt.
        /// </summary>
        internal static string Description_Dirt {
            get {
                return ResourceManager.GetString("Description_Dirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Description_Exit {
            get {
                return ResourceManager.GetString("Description_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fake Exit 1.
        /// </summary>
        internal static string Description_FakeExit1 {
            get {
                return ResourceManager.GetString("Description_FakeExit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fake Exit 2.
        /// </summary>
        internal static string Description_FakeExit2 {
            get {
                return ResourceManager.GetString("Description_FakeExit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        internal static string Description_Fire {
            get {
                return ResourceManager.GetString("Description_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireball - E.
        /// </summary>
        internal static string Description_FireballE {
            get {
                return ResourceManager.GetString("Description_FireballE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireball - N.
        /// </summary>
        internal static string Description_FireballN {
            get {
                return ResourceManager.GetString("Description_FireballN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireball - S.
        /// </summary>
        internal static string Description_FireballS {
            get {
                return ResourceManager.GetString("Description_FireballS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireball - W.
        /// </summary>
        internal static string Description_FireballW {
            get {
                return ResourceManager.GetString("Description_FireballW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Boots.
        /// </summary>
        internal static string Description_FireBoots {
            get {
                return ResourceManager.GetString("Description_FireBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flippers.
        /// </summary>
        internal static string Description_Flippers {
            get {
                return ResourceManager.GetString("Description_Flippers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string Description_Floor {
            get {
                return ResourceManager.GetString("Description_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Floor - E.
        /// </summary>
        internal static string Description_ForceFloorE {
            get {
                return ResourceManager.GetString("Description_ForceFloorE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Floor - N.
        /// </summary>
        internal static string Description_ForceFloorN {
            get {
                return ResourceManager.GetString("Description_ForceFloorN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Floor - Random.
        /// </summary>
        internal static string Description_ForceFloorRandom {
            get {
                return ResourceManager.GetString("Description_ForceFloorRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Floor - S.
        /// </summary>
        internal static string Description_ForceFloorS {
            get {
                return ResourceManager.GetString("Description_ForceFloorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Floor - W.
        /// </summary>
        internal static string Description_ForceFloorW {
            get {
                return ResourceManager.GetString("Description_ForceFloorW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glider - E.
        /// </summary>
        internal static string Description_GliderE {
            get {
                return ResourceManager.GetString("Description_GliderE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glider - N.
        /// </summary>
        internal static string Description_GliderN {
            get {
                return ResourceManager.GetString("Description_GliderN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glider - S.
        /// </summary>
        internal static string Description_GliderS {
            get {
                return ResourceManager.GetString("Description_GliderS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glider - W.
        /// </summary>
        internal static string Description_GliderW {
            get {
                return ResourceManager.GetString("Description_GliderW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravel.
        /// </summary>
        internal static string Description_Gravel {
            get {
                return ResourceManager.GetString("Description_Gravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Button.
        /// </summary>
        internal static string Description_GreenButton {
            get {
                return ResourceManager.GetString("Description_GreenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Key.
        /// </summary>
        internal static string Description_GreenKey {
            get {
                return ResourceManager.GetString("Description_GreenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Lock.
        /// </summary>
        internal static string Description_GreenLock {
            get {
                return ResourceManager.GetString("Description_GreenLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Wall.
        /// </summary>
        internal static string Description_HiddenWall {
            get {
                return ResourceManager.GetString("Description_HiddenWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        internal static string Description_Hint {
            get {
                return ResourceManager.GetString("Description_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice.
        /// </summary>
        internal static string Description_Ice {
            get {
                return ResourceManager.GetString("Description_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice - NE.
        /// </summary>
        internal static string Description_IceNE {
            get {
                return ResourceManager.GetString("Description_IceNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice - NW.
        /// </summary>
        internal static string Description_IceNW {
            get {
                return ResourceManager.GetString("Description_IceNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice - SE.
        /// </summary>
        internal static string Description_IceSE {
            get {
                return ResourceManager.GetString("Description_IceSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Skates.
        /// </summary>
        internal static string Description_IceSkates {
            get {
                return ResourceManager.GetString("Description_IceSkates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice - SW.
        /// </summary>
        internal static string Description_IceSW {
            get {
                return ResourceManager.GetString("Description_IceSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible Wall.
        /// </summary>
        internal static string Description_InvisibleWall {
            get {
                return ResourceManager.GetString("Description_InvisibleWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel - E.
        /// </summary>
        internal static string Description_PanelE {
            get {
                return ResourceManager.GetString("Description_PanelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel - N.
        /// </summary>
        internal static string Description_PanelN {
            get {
                return ResourceManager.GetString("Description_PanelN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel - S.
        /// </summary>
        internal static string Description_PanelS {
            get {
                return ResourceManager.GetString("Description_PanelS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel - SE.
        /// </summary>
        internal static string Description_PanelSE {
            get {
                return ResourceManager.GetString("Description_PanelSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel - W.
        /// </summary>
        internal static string Description_PanelW {
            get {
                return ResourceManager.GetString("Description_PanelW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramecium - E.
        /// </summary>
        internal static string Description_ParameciumE {
            get {
                return ResourceManager.GetString("Description_ParameciumE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramecium - N.
        /// </summary>
        internal static string Description_ParameciumN {
            get {
                return ResourceManager.GetString("Description_ParameciumN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramecium - S.
        /// </summary>
        internal static string Description_ParameciumS {
            get {
                return ResourceManager.GetString("Description_ParameciumS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramecium - W.
        /// </summary>
        internal static string Description_ParameciumW {
            get {
                return ResourceManager.GetString("Description_ParameciumW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink Ball - E.
        /// </summary>
        internal static string Description_PinkBallE {
            get {
                return ResourceManager.GetString("Description_PinkBallE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink Ball - N.
        /// </summary>
        internal static string Description_PinkBallN {
            get {
                return ResourceManager.GetString("Description_PinkBallN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink Ball - S.
        /// </summary>
        internal static string Description_PinkBallS {
            get {
                return ResourceManager.GetString("Description_PinkBallS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink Ball - W.
        /// </summary>
        internal static string Description_PinkBallW {
            get {
                return ResourceManager.GetString("Description_PinkBallW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recessed Wall.
        /// </summary>
        internal static string Description_RecessedWall {
            get {
                return ResourceManager.GetString("Description_RecessedWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Button.
        /// </summary>
        internal static string Description_RedButton {
            get {
                return ResourceManager.GetString("Description_RedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Key.
        /// </summary>
        internal static string Description_RedKey {
            get {
                return ResourceManager.GetString("Description_RedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Lock.
        /// </summary>
        internal static string Description_RedLock {
            get {
                return ResourceManager.GetString("Description_RedLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket.
        /// </summary>
        internal static string Description_Socket {
            get {
                return ResourceManager.GetString("Description_Socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splash.
        /// </summary>
        internal static string Description_Splash {
            get {
                return ResourceManager.GetString("Description_Splash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suction Boots.
        /// </summary>
        internal static string Description_SuctionBoots {
            get {
                return ResourceManager.GetString("Description_SuctionBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank - E.
        /// </summary>
        internal static string Description_TankE {
            get {
                return ResourceManager.GetString("Description_TankE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank - N.
        /// </summary>
        internal static string Description_TankN {
            get {
                return ResourceManager.GetString("Description_TankN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank - S.
        /// </summary>
        internal static string Description_TankS {
            get {
                return ResourceManager.GetString("Description_TankS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank - W.
        /// </summary>
        internal static string Description_TankW {
            get {
                return ResourceManager.GetString("Description_TankW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teeth - E.
        /// </summary>
        internal static string Description_TeethE {
            get {
                return ResourceManager.GetString("Description_TeethE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teeth - N.
        /// </summary>
        internal static string Description_TeethN {
            get {
                return ResourceManager.GetString("Description_TeethN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teeth - S.
        /// </summary>
        internal static string Description_TeethS {
            get {
                return ResourceManager.GetString("Description_TeethS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teeth - W.
        /// </summary>
        internal static string Description_TeethW {
            get {
                return ResourceManager.GetString("Description_TeethW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport.
        /// </summary>
        internal static string Description_Teleport {
            get {
                return ResourceManager.GetString("Description_Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thief.
        /// </summary>
        internal static string Description_Thief {
            get {
                return ResourceManager.GetString("Description_Thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Door - Closed.
        /// </summary>
        internal static string Description_ToggleDoorClosed {
            get {
                return ResourceManager.GetString("Description_ToggleDoorClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Door - Open.
        /// </summary>
        internal static string Description_ToggleDoorOpen {
            get {
                return ResourceManager.GetString("Description_ToggleDoorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trap.
        /// </summary>
        internal static string Description_Trap {
            get {
                return ResourceManager.GetString("Description_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Buffer.
        /// </summary>
        internal static string Description_Unused20 {
            get {
                return ResourceManager.GetString("Description_Unused20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused 36.
        /// </summary>
        internal static string Description_Unused36 {
            get {
                return ResourceManager.GetString("Description_Unused36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused 37.
        /// </summary>
        internal static string Description_Unused37 {
            get {
                return ResourceManager.GetString("Description_Unused37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Block.
        /// </summary>
        internal static string Description_Unused38 {
            get {
                return ResourceManager.GetString("Description_Unused38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walker - E.
        /// </summary>
        internal static string Description_WalkerE {
            get {
                return ResourceManager.GetString("Description_WalkerE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walker - N.
        /// </summary>
        internal static string Description_WalkerN {
            get {
                return ResourceManager.GetString("Description_WalkerN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walker - S.
        /// </summary>
        internal static string Description_WalkerS {
            get {
                return ResourceManager.GetString("Description_WalkerS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walker - W.
        /// </summary>
        internal static string Description_WalkerW {
            get {
                return ResourceManager.GetString("Description_WalkerW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        internal static string Description_Wall {
            get {
                return ResourceManager.GetString("Description_Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string Description_Water {
            get {
                return ResourceManager.GetString("Description_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Key.
        /// </summary>
        internal static string Description_YellowKey {
            get {
                return ResourceManager.GetString("Description_YellowKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Lock.
        /// </summary>
        internal static string Description_YellowLock {
            get {
                return ResourceManager.GetString("Description_YellowLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PreviewTileset {
            get {
                object obj = ResourceManager.GetObject("PreviewTileset", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
